name: Deploy to S3 on Push

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Sync files to S3
      run: |
        aws s3 sync build/ s3://bucket-2025-s3-iam-check --delete
